---
abstract: 'Test Classes the easy way'
author:
  - "Curtis \"Ovid\" Poe <ovid@cpan.org>"
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Class-Most
provides:
  Test::Class::Most:
    file: lib/Test/Class/Most.pm
    version: 0.06
requires:
  Test::Class: 0.33
  Test::Most: 0.21
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/Ovid/Test-Class-Most/
version: 0.06
